import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthCookieSync from "./components/AuthCookieSync";

const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Script inline bloqueante: debe ser el primer hijo de <head> para ejecutarse
// antes del primer paint y evitar el flash de tema claro al recargar en oscuro.
const themeScript = `
(function() {
  try {
    var t = localStorage.getItem('theme');
    var el = document.documentElement;
    if (t === 'dark') {
      el.classList.add('dark');
      el.style.colorScheme = 'dark';
    } else {
      el.classList.remove('dark');
      el.style.colorScheme = 'light';
      if (!t) {
        if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
          el.classList.add('dark');
          el.style.colorScheme = 'dark';
          localStorage.setItem('theme', 'dark');
        } else {
          localStorage.setItem('theme', 'light');
        }
      }
    }
  } catch (e) {
    document.documentElement.classList.remove('dark');
    document.documentElement.style.colorScheme = 'light';
  }
})();
`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{ __html: themeScript }}
          suppressHydrationWarning
        />
      </head>
      <body className={`${inter.variable} font-sans antialiased`}>
        <AuthCookieSync />
        {children}
      </body>
    </html>
  );
}
